# Generated by Django 4.2.6 on 2023-10-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
